services:
  - type: web
    name: studychat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:$PORT "app:app"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER
        value: "true"